<?php
declare(strict_types=1);

namespace BlackCat\Installer\Env;

use BlackCat\Installer\Modules\Module;

final class EnvRenderer
{
    /**
     * @param Module[] $modules
     */
    public function render(array $modules): string
    {
        $lines = [
            '# Generated by blackcat-installer',
            '# ' . date(DATE_ATOM),
        ];
        foreach ($modules as $module) {
            foreach ($module->env() as $key => $value) {
                $lines[] = sprintf('%s=%s', $key, $value);
            }
        }
        $lines[] = '';
        return implode(PHP_EOL, $lines);
    }

    /**
     * @param Module[] $modules
     */
    public function write(string $path, array $modules): void
    {
        $content = $this->render($modules);
        $dir = dirname($path);
        if ($dir !== '' && !is_dir($dir)) {
            if (!@mkdir($dir, 0775, true) && !is_dir($dir)) {
                throw new \RuntimeException("Unable to create directory {$dir}");
            }
        }
        file_put_contents($path, $content);
    }
}
